### PR TITLE
Some comments

### PR DESCRIPTION
**Pull request by Harsh-7070**
Added some comments

### CODE REVIEW

**Review by slimemc-yt — APPROVED** [review]
That looks great 👍🏻

**Comment by Harsh-7070** [comment]
I was just doing timepass 😅

**Comment by AanshumaanShrijaiphysics** [comment]
Wait a minute!!!! you don't need to work on this repo

**Comment by Harsh-7070** [comment]
@AanshumaanShrijaiphysics you can merge this now

**Comment by slimemc-yt** [comment]
oh, okay

**Comment by slimemc-yt** [comment]
I did it

**Comment by Harsh-7070** [comment]
Yeah

**Comment by slimemc-yt** [comment]
harsh check zoom, I've got something there, we can do unlimited messages in slack

**Comment by Harsh-7070** [comment]
I saw that

**Pull request merged**
